### ISSUE TITLE
How to find all ancestors from a person?

### ISSUE THREAD

**Issue by MrBean2016** [TheGeneGenieProject/GeneGenie.Gedcom#101]
I am trying to figure out how to find all ancestors/descendants from a person with this library?
Can this be done with this library or do I need to build the tree first or even load inte to Neo4j ?

Thanks,

**Comment by warthenr** [comment]
There isn't a direct way to do this, but you can loop over each child or parent and work your way up or down.

**Comment by MrBean2016** [comment]
ok, thanks, I will do some experiments.
