### ISSUE TITLE
Temporary ifdef Workaround for XmlNode

### ISSUE THREAD

**Issue by lowenthal-jason** [TheGeneGenieProject/GeneGenie.Gedcom#18]
In order to help with porting this to .Net Core, we need to ifdef() XmlNode and related classes until .Net Standard releases.

**Comment by lowenthal-jason** [comment]
@RyanONeill1970 - go ahead and assign this to me, as I'm actively trying to get the .Net core port working anyway.

Any chance we can add the Hacktober label? :-)

**Comment by RyanONeill1970** [comment]
Possible workaround https://github.com/TheGeneGenieProject/GeneGenie.Gedcom/issues/5#issuecomment-251008210

**Comment by RyanONeill1970** [comment]
No longer required.
