### ISSUE TITLE
Help understanding and implementing Spouse Sealings.

### ISSUE THREAD

**Issue by RyanONeill1970** [TheGeneGenieProject/GeneGenie.Gedcom#2]
GedcomIndividualRecord.cs has TODO markers on the unused variables 'lDSSpouseSealings' and 'lDSIndividualOrdinances'.

Sample GEDCOM files (or snippets) showing this data in use would be appreciated. If possible, unit tests.

**Comment by grantwinney** [comment]
Small point of clarification - the 'lDSIndividualOrdinances' variable is in the GedcomIndividualRecord.cs class.

**Comment by RyanONeill1970** [comment]
Thanks, corrected.

**Comment by RyanONeill1970** [comment]
Unless anyone else is going for this, I'll grab it myself. Should just be a case of a) Finding public sample files or b) Creating a sample file with Family Tree Maker (or other utility).
