### ISSUE TITLE
Fix Compilation Warnings

### ISSUE THREAD

**Issue by sgaulding** [TheGeneGenieProject/GeneGenie.Gedcom#32]
I think this is can be associated with issue #7.

Reduce compilation warnings found in [AppVeyor Build Messages](https://ci.appveyor.com/project/RyanONeill1970/genegenie-gedcom/build/messages)

Example:
![appveyor screenshot](https://cloud.githubusercontent.com/assets/2135515/19294753/251b0890-8ff5-11e6-8464-d395a5c03ae8.png)

**Comment by RyanONeill1970** [comment]
Thanks @sgaulding. You are correct, the other bits to fix the NotImplemented are covered as issues #2, #3 and #4. I'll leave it up to you if you want to close this or add to it.

**Comment by sgaulding** [comment]
@RyanONeill1970: I'm going to close this since the other warnings are covered by other issues.

**Comment by sgaulding** [comment]
Going to reopen until PR #33 has been finished. I wasn't sure if I close this would effect PR #33.

**Comment by sgaulding** [comment]
#33 Merged
