### ISSUE TITLE
Implement French Revolutionary calendar parsing.

### ISSUE THREAD

**Issue by RyanONeill1970** [TheGeneGenieProject/GeneGenie.Gedcom#4]
**If you are a French speaker, your input would be most appreciated.**

In GedcomDate.cs we have '// TODO: no FrenCalendar!' and the variable calendar is not set.

It looks like this is only used to handle resolving the number of days per month in GetDateInfo and for setting the calendar of the returned date.

I can't see how a French calendar will be any different to a standard English one but I may be missing something.

We need;
1. To know whether French and English calendars are functionally equivalent.
2. If not equivalent, we need test data and a unit test to show the issue.

**Comment by AntoineGa** [comment]
Hi, i think it's a reference to the calendar used during the French Revolution : https://en.wikipedia.org/wiki/French_Republican_Calendar

**Comment by RyanONeill1970** [comment]
You're correct. I can't imagine a whole family tree file encoded with dates in this format unless they are limited to the date range that the calendar was in force.

Thank you @AntoineGa , I'll take a look at getting some sample data now.

**Comment by RyanONeill1970** [comment]
Closing, if anyone needs this, please re-open.
