### ISSUE TITLE
Dot Net Core and 4.5.2 simultaneous build.

### ISSUE THREAD

**Issue by RyanONeill1970** [TheGeneGenieProject/GeneGenie.Gedcom#5]
The goal is to have a single Nuget package created with binaries for both frameworks.

Dot Net 4.5.2 is the earliest we can target as that is the lowest supported by Microsoft.

The tooling for specifying the build is still a mess in Visual Studio and hard to fathom what is the official supported way.

**Comment by diegobrum** [comment]
Just a ideia...
If you change your projects from .csproj to .xproj, and configure project.json like bellow, and run `dotnet pack project.json --configuration release --output .`, you gotch this in a simple way with a great VS support :)

```json
{
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.Extensions.DependencyInjection": "1.0.0",
        "Microsoft.Extensions.Options": "1.0.0",
        "Newtonsoft.Json": "9.0.1",
        "System.Console": "4.0.0",
        "System.Diagnostics.Tools": "4.0.1",
        "System.IO": "4.1.0",
        "System.IO.FileSystem": "4.0.1"
      }
    },
    "net452": {
      "dependencies": {
        "Newtonsoft.Json": "9.0.1",
        "SimpleInjector": "3.2.0"
      }
    }
  },
  "packOptions": {
    "licenseUrl": "<LINK>",
    "repository": {
      "url": "<LINK>",
      "type": "git"
    },
    "tags": [ "TAG#1", "TAG#1" ],
    "requireLicenseAcceptance": false
  }
}
```

**Comment by RyanONeill1970** [comment]
Thanks, I had a look at that and got stuck with the DateTime library not having calendars anymore. The overloads are there in System.Runtime which is referenced from Nuget. I can see the methods when using the object browser but they just won't come into scope for compilation. I'll have a fiddle some more.

**Comment by diegobrum** [comment]
Do you talking about https://github.com/TheGeneGenieProject/GeneGenie.Gedcom/blob/master/GeneGenie.Gedcom/GedcomDate.cs :1024???

If yes, in CoreClr you need to change

From:
```csharp
var calendar = new GregorianCalendar();
new DateTime(y, m, d, calendar);
```

To:
```csharp
using System.Globalization;
...
var calendar = new GregorianCalendar();
calendar.ToDateTime(y, m, d);
```

**Comment by RyanONeill1970** [comment]
That makes sense. Do you know why I could see the overloaded version with the calendar parameter but not use it?

I see it in the full core reference docs here https://docs.microsoft.com/en-us/dotnet/core/api/system.datetime#System_DateTime__ctor_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Globalization_Calendar_

**Comment by lowenthal-jason** [comment]
Something else I'm seeing as I'm fiddling with porting this into .Net core is that, as of right now, .Net Core isn't supporting XmlNode.

I _think_ this explains the problem? https://github.com/dotnet/corefx/issues/11888

**Comment by RyanONeill1970** [comment]
Odd, I did hear that it was not in there but then I ran the portability analyser and it seemed OK.

I've just checked again and the portability tests report 100%, but against .Net Standard v2.0 which is what you pointed to. I assumed it was running against the 1.6 profile.

We could ifdef them out for the moment, seeing as it's not released and create an issue to track it. What do you think?

.Net Standard is due to be released with Visual Studio 15 which I'm hoping is sometime this year.

**Comment by diegobrum** [comment]
Hup!
@RyanONeill1970 

> That makes sense. Do you know why I could see the overloaded version with the calendar parameter but not use it?

Don't know.... may be outdated doc or a internal method

@lowenthal-jason
> Something else I'm seeing as I'm fiddling with porting this into .Net core is that, as of right now, .Net Core isn't supporting XmlNode.

I used XDocument since Net 4.0 (I think) and works well in CoreClr

**Comment by RyanONeill1970** [comment]
Closed as we now have a .Net Standard version.
