### ISSUE TITLE
NET Standard / NET Core version?

### ISSUE THREAD

**Issue by KvanTTT** [TheGeneGenieProject/GeneGenie.Gedcom#53]

**Comment by RyanONeill1970** [comment]
I can certainly look at this. Is there a particular version of .Net standard that you'd want to target?

**Comment by KvanTTT** [comment]
No, I'm using the latest 2.0.

**Comment by RyanONeill1970** [comment]
I have a version working with .Net Standard 2.0 now and passing most tests.

The only tests remaining with an issue are ones for reading files encoded with IBMPC encoding (code page 437). I can fix these tomorrow. Do you know what code pages your source GEDCOM files use?

Looking at the test code coverage, I could do with testing GEDCOM files with 1252 and UTF8 encoding too. If you have some sample files hanging around, I'd be appreciative of them.

**Comment by fire-eggs** [comment]
Here is a selection of GED files from the interwebs. I hope they prove useful.

[utf8.zip](https://github.com/TheGeneGenieProject/GeneGenie.Gedcom/files/2325924/utf8.zip)
[ansi.zip](https://github.com/TheGeneGenieProject/GeneGenie.Gedcom/files/2325925/ansi.zip)

**Comment by KvanTTT** [comment]
I think I use the GEDCOM file with one of the standard encodings. IBMPC looks very exotic.

**Comment by RyanONeill1970** [comment]
There are issues with ANSI encoding and I've not tested UTF8, but the latest should work as a core reference. Can you try and let me know? If all goes well, I'll get the remaining tests worked out and publish a nuget package.

Would be interested in your feedback.

**Comment by RyanONeill1970** [comment]
ANSI is complete, should be good to use for core.

I'll make a nuget in a few days.
