### ISSUE TITLE
Continuos Integration Tool

### ISSUE THREAD

**Issue by guilhermeddf** [TheGeneGenieProject/GeneGenie.Gedcom#58]
Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

**Comment by RyanONeill1970** [comment]
Hi, yes it does and it is all online. It uses appveyor which you can see at the bottom of https://github.com/TheGeneGenieProject/GeneGenie.Gedcom. Static analysis is also run by SonarCloud and those results are also visible on that page.

**Comment by guilhermeddf** [comment]
Thank you!
