### ISSUE TITLE
Create nuget package.

### ISSUE THREAD

**Issue by RyanONeill1970** [TheGeneGenieProject/GeneGenie.Gedcom#8]
I'd like to follow the method used here 
http://brian-federici.com/blog/2013/4/17/automatically-target-multiple-frameworks-in-your-nuget-package for splitting between beta and ready to use packages.

**Comment by M3LiNdRu** [comment]
Hi, I would say I can figure out your issue.

Let me a couple of days and I will send you a PR

**Comment by RyanONeill1970** [comment]
That would be brilliant, thank you very much for helping.

**Comment by gep13** [comment]
@RyanONeill1970 assuming you are planning on using Cake, some of the steps, i.e. The msbuild steps, in that article wouldn't be required.

**Comment by jeromechrist** [comment]
Willing to take this one as well unless @M3LiNdRu has Work in Progress for this :blush:

To clarify the need : what do you want in your nuget package ? 

- Everything defined in the 3 .nuspecs in 1 package or 1 package per .nuspec ? 

We should also add build targets net40/net45/net46 in the cake build added by #17

**Comment by M3LiNdRu** [comment]
@jeromechrist  I´m currently working on this.

I'm refactoring build.cake for creating packages during build. Right now, 1 package per .nuspec

**Comment by M3LiNdRu** [comment]
FYI let you know that the current license is included in the nugets.

build.cake for development and build_nuget.cake for tagged builds

**Comment by gep13** [comment]
>@M3LiNdRu said...
build.cake for development and build_nuget.cake for tagged builds

Is there a reason that you have created two cake files?  Why not a single one, with different entry points?

**Comment by M3LiNdRu** [comment]
Of course it can be merged in one file. If you think it's better, you can
go ahead ;)

El dia 22/10/2016 9:05 p. m., "Gary Ewan Park" <notifications@github.com>
va escriure:
