### ISSUE TITLE
ChangeDate: Wrong culture and time in output

### ISSUE THREAD

**Issue by OkapiD** [TheGeneGenieProject/GeneGenie.Gedcom#82]
Automatically created ChangeDate has German culture in Output:

1 CHAN 
2 DATE 01 **Mai** 2020
3 TIME 06:36:35

The time should be pm in that case.

Maybe that way: 

1 CHAN 
2 DATE 01 May 2020
3 TIME 18:36:35

**Comment by OkapiD** [comment]
At some place in library

                ChangeDate.Date1 = now.ToString("dd MMM yyyy");
                ChangeDate.Time = now.ToString("hh:mm:ss");

should be maybe

                ChangeDate.Date1 = now.ToString("dd MMM yyyy", **CultureInfo.InvariantCulture**);
                ChangeDate.Time = now.ToString("**HH**:mm:ss", **CultureInfo.InvariantCulture**);

**Comment by RyanONeill1970** [comment]
Thanks for that, now corrected with unit tests.
