### ISSUE TITLE
GedComName, Property Name, Set: Problems with additional spaces

### ISSUE THREAD

**Issue by OkapiD** [TheGeneGenieProject/GeneGenie.Gedcom#86]
If you have a NAME tag, formatted with slashes at surname and additional leading spaces like

givenname /  surname/

parsing is incorrect. you get some additional repeated characters at the end of NAME line.

My quick and dirty solution (working for me) is to remove spaces near slashes and double spaces in property Name, set:

while (name.Contains("  ")) name = name.Replace("  ", " ");
while (name.Contains("/ ")) name = name.Replace("/ ", "/");
while (name.Contains(" /")) name = name.Replace(" /", "/");

**Comment by RyanONeill1970** [comment]
I'll have a look. Sorry the slow reply, I've been looking at building a GEDCOM parser in F# instead (for code quality reason mostly).

If you have unit tests for any of these then that would be helpful too.

**Comment by OkapiD** [comment]
Thank you for reply. No further problems after my workarounds. The api is working great for my purpose. But maybe my experiences can help to improve it a little bit.
I apologize for only sending the bug reports resp. the feature idea. I am not familiar with tests and the api internals.

**Comment by RyanONeill1970** [comment]
Are you able to share a GEDCOM file which demonstrates this? I've been importing ones with leading and trailing spaces and it seems OK. So I'm probably not testing for the exact same conditions as you are finding. It does trim the spaces, which I think is incorrect if they are quoted with slashes.

**Comment by OkapiD** [comment]
If you have in Gedcom input

1 NAME Peter /    Olsen/

than you have in Gedcom output:

1 NAME Peter /Olsen/ sen/

Am Mo., 13. Juli 2020 um 12:22 Uhr schrieb RyanONeill1970 <
notifications@github.com>:

**Comment by RyanONeill1970** [comment]
Thanks, it is resolved now. New build going through and nuget should come out the other end in 30 minutes.
