### ISSUE TITLE
Update nuget release notes as part of build.

### ISSUE THREAD

**Issue by RyanONeill1970** [TheGeneGenieProject/GeneGenie.Gedcom#9]
Obviously, after the nuget package has been created.

See https://github.com/DefinitelyTyped/NugetAutomation/blob/master/CreatePackages.ps1 for how this might be done.

**Comment by gep13** [comment]
@RyanONeill1970 are you talking about adding releasenotes into the nuspec file that is used to generate the nupkg package? Or something else?

**Comment by RyanONeill1970** [comment]
Yes, I'd like to automate that step so that it's not left up to a human to forget to update the nuget package. Also stops them putting 'bug fixes' as a comment.

**Comment by gep13** [comment]
Where do you currently keep you release notes?

**Comment by RyanONeill1970** [comment]
No releases so far, so no notes. I was going to pull them off the commit messages up until the last tagged release and use tags to kick off the package process.

**Comment by gep13** [comment]
Do you use GitHub Milestones, and associate issues with Milestones? If so, GitReleaseManager could be a good fit for you? That is what we use in Cake and does essentially what you are describing.

**Comment by RyanONeill1970** [comment]
We don't, but will now. Thanks for that.
